# Generated by Django 4.2.15 on 2024-08-24 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colony_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollenProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=50)),
                ('total_pollen', models.FloatField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='apicultura.colony')),
            ],
        ),
        migrations.CreateModel(
            name='ColonyStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('colony_health', models.CharField(choices=[('Saludable', 'Saludable'), ('Muerta', 'Muerta'), ('Débil', 'Débil')], max_length=50)),
                ('num_of_bees', models.IntegerField()),
                ('queen_present', models.BooleanField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='apicultura.colony')),
            ],
        ),
        migrations.CreateModel(
            name='ColonyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('colony_temperature', models.FloatField()),
                ('colony_humidity', models.FloatField()),
                ('ambient_temperature', models.FloatField()),
                ('ambient_humidity', models.FloatField()),
                ('weight', models.FloatField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='apicultura.colony')),
                ('colony_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='apicultura.colonystatushistory')),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonies', to='apicultura.hive'),
        ),
    ]
