# Generated by Django 4.2.15 on 2024-08-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colony_number', models.IntegerField()),
                ('colony_health', models.CharField(max_length=50)),
                ('num_of_bees', models.IntegerField()),
                ('queen_present', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollenProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=50)),
                ('total_pollen', models.FloatField()),
                ('pollen_quality', models.CharField(max_length=50)),
                ('stocks', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('production_value', models.FloatField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='apicultura.colony')),
            ],
        ),
        migrations.CreateModel(
            name='ColonyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('apparent_temperature', models.FloatField()),
                ('ambient_temperature', models.FloatField()),
                ('ambient_humidity', models.FloatField()),
                ('temperature_difference', models.FloatField()),
                ('apparent_temperature_difference', models.FloatField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='apicultura.colony')),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonies', to='apicultura.hive'),
        ),
    ]
