# Generated by Django 4.2.15 on 2024-08-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicultura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonymonitoring',
            name='apparent_temperature',
        ),
        migrations.RemoveField(
            model_name='colonymonitoring',
            name='apparent_temperature_difference',
        ),
        migrations.RemoveField(
            model_name='colonymonitoring',
            name='temperature_difference',
        ),
        migrations.RemoveField(
            model_name='pollenproduction',
            name='pollen_quality',
        ),
        migrations.RemoveField(
            model_name='pollenproduction',
            name='price_per_kg',
        ),
        migrations.RemoveField(
            model_name='pollenproduction',
            name='production_value',
        ),
        migrations.RemoveField(
            model_name='pollenproduction',
            name='stocks',
        ),
        migrations.AddField(
            model_name='colonymonitoring',
            name='weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
